// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhy0rw5p6teuS2RGkMFD4XrWBFwsP4XE',
    appId: '1:1001543475854:web:3e854370e1e5b522931fdf',
    messagingSenderId: '1001543475854',
    projectId: 'elearn-c39c3',
    authDomain: 'elearn-c39c3.firebaseapp.com',
    storageBucket: 'elearn-c39c3.appspot.com',
    measurementId: 'G-3QQ7SYSK1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9sd8cTxIZ8vBHRETUe9O2oTTO4MJHZu0',
    appId: '1:1001543475854:android:75e14c80f90798d8931fdf',
    messagingSenderId: '1001543475854',
    projectId: 'elearn-c39c3',
    storageBucket: 'elearn-c39c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-BnK97xaP_VSzgNWUbNTTG12f0fbXs4',
    appId: '1:1001543475854:ios:e5e1998ca8e235b1931fdf',
    messagingSenderId: '1001543475854',
    projectId: 'elearn-c39c3',
    storageBucket: 'elearn-c39c3.appspot.com',
    iosBundleId: 'com.example.ck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7-BnK97xaP_VSzgNWUbNTTG12f0fbXs4',
    appId: '1:1001543475854:ios:e5e1998ca8e235b1931fdf',
    messagingSenderId: '1001543475854',
    projectId: 'elearn-c39c3',
    storageBucket: 'elearn-c39c3.appspot.com',
    iosBundleId: 'com.example.ck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuhy0rw5p6teuS2RGkMFD4XrWBFwsP4XE',
    appId: '1:1001543475854:web:70c9c6a28785a7c5931fdf',
    messagingSenderId: '1001543475854',
    projectId: 'elearn-c39c3',
    authDomain: 'elearn-c39c3.firebaseapp.com',
    storageBucket: 'elearn-c39c3.appspot.com',
    measurementId: 'G-FEVC842RJE',
  );
}
